/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;
import java.awt.Color;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.border.LineBorder;
import javax.swing.text.Document;

/**
 *
 * @author DELL
 */
public class LoginForm extends javax.swing.JDialog {

    /**
     * Creates new form LoginForm
     */
    String strUserName = " Username";
    String strPw = "password";
    public LoginForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Login Form");
        setLocationRelativeTo(null);   
        getContentPane().setBackground(new java.awt.Color(245, 245, 245));
//        txtSearch.setBackground(new java.awt.Color(239, 239, 239));
        setPlaceholder();
        designBtn();       
    }
    public void setPlaceholder() {
        LineBorder lineBorder = new LineBorder(Color.white, 15, true);
        txtUserName.setBorder(lineBorder);
        txtPw.setBorder(lineBorder);
        // Set username
        txtUserName.setText(strUserName);
        txtUserName.setForeground(new java.awt.Color(170, 170, 170));
        // Set pw
        txtPw.setText(strPw);
        txtPw.setForeground(new java.awt.Color(170, 170, 170));
//        new java.awt.Color(255, 237, 94)
        // Set init Error
        lblErrPw.setText("");
        lblErrUser.setText("");
    }
    public void designBtn() {
        LineBorder lineBorder =new LineBorder(new java.awt.Color(30, 150, 249), 15, true);
        btnLogin.setBackground(new java.awt.Color(12, 125, 212));
        btnLogin.setForeground(Color.white);
        btnLogin.setBorder(lineBorder);
        
    }
    public boolean validateUserName() {
        boolean isValid = false;
        LineBorder lineBorder =new LineBorder(new java.awt.Color(255, 237, 94), 15, true);
        if(strUserName.equalsIgnoreCase(txtUserName.getText())) {
            lblErrUser.setText("Vui lòng nhập tài khoản!");
            lblErrUser.setForeground(new java.awt.Color(255, 51, 51));
            txtUserName.setBorder(lineBorder);
            txtUserName.setBackground(new java.awt.Color(255, 237, 94));
            isValid = true;
        }
        return isValid;
    }
    public boolean validatePw() {
        boolean isValid = false;
        LineBorder lineBorder =new LineBorder(new java.awt.Color(255, 237, 94), 15, true);
        if(new String(txtPw.getPassword()).equalsIgnoreCase(strPw)) {
            lblErrPw.setText("Vui lòng nhập mật khẩu!");
            lblErrPw.setForeground(new java.awt.Color(255, 51, 51));
            txtPw.setBorder(lineBorder);
            txtPw.setBackground(new java.awt.Color(255, 237, 94));
            isValid = true;
        }
        return isValid;
    }
    public void validateAll() {
        boolean isFormValid = true;
        if(validateUserName()) {
            isFormValid = false;
        }
        if(validatePw()) {
            isFormValid = false;
        }
        if(isFormValid) {
            // Todo Code
        }
    }
     public void forgotPw() {
        FormForgotPw forgotPw = new FormForgotPw(null, true);
        forgotPw.setVisible(true);
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlLoginForm = new javax.swing.JPanel();
        lblAvatar = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        lblTitle = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        txtPw = new javax.swing.JPasswordField();
        lblErrUser = new javax.swing.JLabel();
        lblErrPw = new javax.swing.JLabel();
        lblForgotPw = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblRegistration = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlLoginForm.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        pnlLoginForm.setPreferredSize(new java.awt.Dimension(824, 633));

        lblAvatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/avartar-boy2.png"))); // NOI18N

        txtUserName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtUserName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUserNameFocusLost(evt);
            }
        });
        txtUserName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUserNameKeyTyped(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 27)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("User Login");

        btnLogin.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        txtPw.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtPw.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPwFocusLost(evt);
            }
        });
        txtPw.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPwKeyTyped(evt);
            }
        });

        lblErrUser.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblErrUser.setText("Error Message");

        lblErrPw.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblErrPw.setText("Error Message");

        lblForgotPw.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblForgotPw.setForeground(new java.awt.Color(204, 51, 0));
        lblForgotPw.setText("Quên mật khẩu?");
        lblForgotPw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblForgotPwMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel1.setText("Bạn chưa có tài khoản?");

        lblRegistration.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblRegistration.setForeground(new java.awt.Color(204, 51, 0));
        lblRegistration.setText("Đăng ký");
        lblRegistration.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegistrationMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlLoginFormLayout = new javax.swing.GroupLayout(pnlLoginForm);
        pnlLoginForm.setLayout(pnlLoginFormLayout);
        pnlLoginFormLayout.setHorizontalGroup(
            pnlLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginFormLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(lblAvatar)
                .addGap(57, 57, 57)
                .addGroup(pnlLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLoginFormLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(lblRegistration))
                    .addGroup(pnlLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                        .addGroup(pnlLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblErrUser)
                            .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPw, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblErrPw, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jSeparator1)))
                .addContainerGap(66, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginFormLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblForgotPw)
                .addGap(113, 113, 113))
        );
        pnlLoginFormLayout.setVerticalGroup(
            pnlLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginFormLayout.createSequentialGroup()
                .addGroup(pnlLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLoginFormLayout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(lblAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlLoginFormLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(lblTitle)
                        .addGap(18, 18, 18)
                        .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblErrUser)
                        .addGap(23, 23, 23)
                        .addComponent(txtPw, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblErrPw)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblForgotPw)
                .addGap(5, 5, 5)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblRegistration))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlLoginForm, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlLoginForm, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserNameKeyTyped
        // Set username
        LineBorder lineBorder =new LineBorder(Color.white, 15, true);
        txtUserName.setBorder(lineBorder);
        txtUserName.setBackground(Color.white);
        lblErrUser.setText("");
        if(txtUserName.getText().equalsIgnoreCase(strUserName)) {
            txtUserName.setText("");
            txtUserName.setForeground(Color.black);
        } else if(txtUserName.getText().equalsIgnoreCase("")) {
            txtUserName.setText(strUserName);
            txtUserName.setForeground(new java.awt.Color(170, 170, 170));
        }
    }//GEN-LAST:event_txtUserNameKeyTyped

    private void txtUserNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUserNameFocusLost
            validateUserName();
    }//GEN-LAST:event_txtUserNameFocusLost

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        validateAll();
    }//GEN-LAST:event_btnLoginActionPerformed

    private void txtPwKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPwKeyTyped
        LineBorder lineBorder =new LineBorder(Color.white, 15, true);
        txtPw.setBorder(lineBorder);
        txtPw.setBackground(Color.white);
        
        lblErrPw.setText("");
        if(new String(txtPw.getPassword()).equalsIgnoreCase(strPw)) {
            txtPw.setText("");
            txtPw.setForeground(Color.black);
            
        } else if(new String(txtPw.getPassword()).equalsIgnoreCase("")) {
            txtPw.setText(strPw);
            txtPw.setForeground(new java.awt.Color(170, 170, 170));
        }
//        JOptionPane.showMessageDialog(this, new String(txtPw.getPassword()));
    }//GEN-LAST:event_txtPwKeyTyped

    private void txtPwFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPwFocusLost
        validatePw();
    }//GEN-LAST:event_txtPwFocusLost

    private void lblForgotPwMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblForgotPwMouseClicked
        forgotPw();
    }//GEN-LAST:event_lblForgotPwMouseClicked

    private void lblRegistrationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistrationMouseClicked
        MemberRegister mr = new MemberRegister();
        this.dispose();
        mr.setVisible(true);
    }//GEN-LAST:event_lblRegistrationMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LoginForm dialog = new LoginForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAvatar;
    private javax.swing.JLabel lblErrPw;
    private javax.swing.JLabel lblErrUser;
    private javax.swing.JLabel lblForgotPw;
    private javax.swing.JLabel lblRegistration;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlLoginForm;
    private javax.swing.JPasswordField txtPw;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
